import React, { createContext, useState } from "react";
import initialProducts from "../data/products";

export const ProductContext = createContext();

export function ProductProvider({ children }) {
  const [products, setProducts] = useState(initialProducts);

  // add a product (id autogenerated)
  function addProduct(newProduct) {
    const id = Date.now().toString();
    setProducts(prev => [...prev, { ...newProduct, id }]);
  }

  // update product qty (for future use)
  function updateProduct(id, updates) {
    setProducts(prev => prev.map(p => (p.id === id ? { ...p, ...updates } : p)));
  }

  return (
    <ProductContext.Provider value={{ products, addProduct, updateProduct }}>
      {children}
    </ProductContext.Provider>
  );
}
